- https://wikidocs.net/52460

## 2. 넘파이로 텐서 만들기 (벡터와 행렬 만들기)

In [3]:
import numpy as np

### 1) 1D with Numpy

In [6]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함.
t

array([0., 1., 2., 3., 4., 5., 6.])

In [8]:
print("Rank of t :", t.ndim)
print("Shape of t :", t.shape)

Rank of t : 1
Shape of t : (7,)


#### 1-1) Numpy 기초 이해하기

In [11]:
print("t[0] t[1] t[-1] = ", t[0], t[1], t[-1])  # 인덱스를 통한 원소 접근

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [13]:
print("t[2:5] t[4:-1] = ", t[2:5], t[4:-1])  # [시작 번호 : 끝 번호]로 범위 지정을 통해 가져온다.

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [15]:
print("t[:2] t[3:] = ", t[:2], t[3:])  # 시작 번호를 생략한 경우와 끝 번호를 생략한 경우

t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


## 3. 파이토치 텐서 선언하기(PyTorch Tensor Allocation)

In [18]:
import torch

### 1) 1D with PyTorch

In [21]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [25]:
print(t.dim())   # rank. 즉, 차원
print(t.shape)   # shape
print(t.size())  # shape

1
torch.Size([7])
torch.Size([7])


In [27]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2) 2D with PyTorch

In [30]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [32]:
print(t.dim())   # rank. 즉, 차원
print(t.size())  # shape

2
torch.Size([4, 3])


In [34]:
print(t[:, 1])         # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, 1].size())  # ↑ 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [36]:
print(t[:, :-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### 3) 브로드캐스팅(Broadcasting)

In [39]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
m1 + m2

tensor([[5., 5.]])

In [41]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])  # [3] -> [3, 3]
m1 + m2

tensor([[4., 5.]])

In [43]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
m1 + m2

tensor([[4., 5.],
        [5., 6.]])

In [45]:
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

## 4. 자주 사용되는 기능들

### 1) 행렬 곱셈과 곱셈의 차이(Matrix Multiplication Vs. Multiplication)

In [49]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print("Shape of Matrix 1 :", m1.shape)  # 2 x 2
print("Shape of Matrix 2 :", m2.shape)  # 2 x 1
print(m1.matmul(m2))  # 2 x 1

Shape of Matrix 1 : torch.Size([2, 2])
Shape of Matrix 2 : torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [51]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### 2) 평균(Mean)

In [55]:
t = torch.FloatTensor([1, 2])
t.mean()

tensor(1.5000)

In [57]:
t = torch.FloatTensor([[1, 2], [3, 4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [59]:
t.mean()

tensor(2.5000)

In [61]:
t.mean(dim=0)

tensor([2., 3.])

In [63]:
t.mean(dim=1)

tensor([1.5000, 3.5000])

In [65]:
t.mean(dim=-1)

tensor([1.5000, 3.5000])

### 3) 덧셈(Sum)

In [68]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [70]:
print(t.sum())       # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0))  # 행을 제거
print(t.sum(dim=1))  # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### 4) 최대(Max)와 아그맥스(ArgMax)

In [73]:
t = torch.FloatTensor([[1, 2], [3, 4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [75]:
t.max()  # Returns one value: max

tensor(4.)

In [77]:
t.max(dim=0)  # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [79]:
print("Max :", t.max(dim=0)[0])
print("Argmax :", t.max(dim=0)[1])

Max : tensor([3., 4.])
Argmax : tensor([1, 1])


In [81]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### 5) 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요!

In [84]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [86]:
ft.shape

torch.Size([2, 2, 3])

In [88]:
print(ft.view([-1, 3]))  # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [90]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 6) 스퀴즈(Squeeze) - 1인 차원을 제거한다.

In [93]:
ft = torch.FloatTensor([[0], [1], [2]])

print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [95]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### 7) 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.

In [98]:
ft = torch.Tensor([0, 1, 2])
ft.shape

torch.Size([3])

In [100]:
print(ft.unsqueeze(0))  # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [102]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [104]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [106]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### 8) 타입 캐스팅(Type Casting)

In [109]:
lt = torch.LongTensor([1, 2, 3, 4])
lt

tensor([1, 2, 3, 4])

In [111]:
lt.float()

tensor([1., 2., 3., 4.])

In [113]:
bt = torch.ByteTensor([True, False, False, True])
bt

tensor([1, 0, 0, 1], dtype=torch.uint8)

In [115]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### 9) 연결하기(concatenate)

In [118]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [120]:
torch.cat([x, y], dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [122]:
torch.cat([x, y], dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

### 10) 스택킹(Stacking)

In [125]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [127]:
torch.stack([x, y, z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [131]:
torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [133]:
torch.stack([x, y, z], dim=1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### 11) ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서

In [136]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
x

tensor([[0., 1., 2.],
        [2., 1., 0.]])

In [138]:
torch.ones_like(x)  # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [140]:
torch.zeros_like(x)  # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### 12) In-place Operation (덮어쓰기 연산)

In [143]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [145]:
print(x.mul(2.))  # 곱하기 2를 수행한 결과를 출력
print(x)          # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [147]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x)           # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
