In [1]:
import numpy as np

# **넘파이 배열의 구조**

- 넘파이 모듈의 기본 배열은 ndarray(n-dimension array, 다차원 배열)

## 다차원배열 변환

- np.array() : 다차원 배열을 만드는 함수

In [5]:
li = [1, 2, 3, 4]
li_arr = np.array(li)

In [7]:
li_arr

array([1, 2, 3, 4])

In [9]:
type(li_arr)

numpy.ndarray

In [11]:
# 튜플을 다차원배열로 변환
tu = (1, 2, 3, 4)
tu_arr = np.array(tu)

In [13]:
tu_arr

array([1, 2, 3, 4])

In [15]:
type(tu_arr)

numpy.ndarray

- 배열도 mutable 의 특징을 가짐
    - 변수를 다른 변수에 복사한 뒤 데이터를 수정하면 모든 변수의 데이터가 수정됨

In [18]:
co_arr = li_arr
id(co_arr), id(li_arr)

(1910545627632, 1910545627632)

In [20]:
co_arr

array([1, 2, 3, 4])

In [22]:
co_arr[0] = 100

In [24]:
co_arr

array([100,   2,   3,   4])

In [26]:
li_arr

array([100,   2,   3,   4])

In [28]:
# 다차원 배열의 값을 복사해서 새로운 배열을 만들면
# 동일한 값을 가진 새로운 배열을 만들어지기 때문에 서로 다른 데이터가 됨
new_arr = np.array(li_arr)

In [30]:
id(new_arr), id(li_arr)

(1910545627440, 1910545627632)

In [32]:
new_arr[0] = 99

In [34]:
new_arr

array([99,  2,  3,  4])

In [36]:
li_arr

array([100,   2,   3,   4])

- 파이썬 리스트는 다양한 자료형을 사용할 수 있지만 넘파이 배열은 같은 자료형만 넣을 수 있음
    - 다차원 배열을 생성할 때 자료형을 지정하지 않으면 내부의 원소를 보고 자동으로 추론해서 만듦

In [39]:
# float 자료형을 지정해서 다차원배열 만들기
fl_arr = np.array(li, dtype = float)

In [41]:
fl_arr

array([1., 2., 3., 4.])

In [43]:
fl_arr.dtype

dtype('float64')

- 2차원배열이란
    - 2개의 축을 가지는 배열(행, 열)
        - 두 개의 1차원 배열이 쌓여서 하나의 2차원 배열이 만들어짐

In [46]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

In [48]:
# 각 축의 원소의 개수
arr2d.shape

(2, 3)

In [50]:
# 축의 개수
arr2d.ndim

2

In [52]:
arr2d.dtype

dtype('int32')

In [54]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
# 다차원 배열을 1차원 배열로 조회
arr2d.flatten()

array([1, 2, 3, 4, 5, 6])

## 배열에서 원소 조회하기

In [59]:
# 1차원 배열
li_arr

array([100,   2,   3,   4])

In [61]:
li

[1, 2, 3, 4]

In [63]:
li[0]

1

In [65]:
li_arr[0]

100

In [67]:
# 다차원배열에서 원소 조회
list2d = arr2d.tolist() # 배열을 리스트로 변환

In [69]:
list2d

[[1, 2, 3], [4, 5, 6]]

In [71]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
# 리스트는 정수만 이용해서 원소 조회 가능
# 따라서 리스트 내 리스트의 원소를 조회할 때는 인덱싱을 두 번 사용해야함
list2d[0][1]

2

In [75]:
list2d[0, 1]

TypeError: list indices must be integers or slices, not tuple

In [77]:
# 다차원 배열은 행과 열의 인덱스를 튜플로 조회할 수 있음
arr2d[0, 1]

2

In [79]:
arr2d[0][1]

2

### - 슬라이싱

In [83]:
arr1 = np.array([[0, 1, 2, 3],
                 [4, 5, 6, 7]])

In [85]:
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [87]:
arr1.shape

(2, 4)

In [89]:
# 첫번째 행 전체
arr1[0, :]

array([0, 1, 2, 3])

In [91]:
# 두 번째 열 전체
arr1[:, 1]

array([1, 5])

In [93]:
# 두 번째 행의 두 번째 열부터 끝 열까지
arr1[1, 1:]

array([5, 6, 7])

In [95]:
# 각 행의 두 번째 열까지
arr1[:, :2]

array([[0, 1],
       [4, 5]])

#### 문제

1. 아래의 행렬에서 값 7을 인덱싱

2. 아래의 행렬에서 값 14를 인덱싱

3. 아래의 행렬에서 배열 [6, 7] 을 슬라이싱

4. 아래의 행렬에서 배열 [7, 12] 를 슬라이싱

5. 아래의 행렬에서 배열 [[3, 4], [8, 9]] 를 슬라이싱

In [98]:
m = np.arange(15).reshape(3, -1)

In [100]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [102]:
# 1. 아래의 행렬에서 값 7을 인덱싱
m[1, 2]

7

In [104]:
# 2. 아래의 행렬에서 값 14를 인덱싱
m[2, 4]

14

In [106]:
# 3. 아래의 행렬에서 배열 [6, 7] 을 슬라이싱
m[1, 1:3]

array([6, 7])

In [108]:
# 4. 아래의 행렬에서 배열 [7, 12] 를 슬라이싱
m[1:, 2]

array([ 7, 12])

In [110]:
# 5. 아래의 행렬에서 배열 [[3, 4], [8, 9]] 를 슬라이싱
m[:2, 3:]

array([[3, 4],
       [8, 9]])

1. 아래의 행렬에서 배열 [8, 14] 를 슬라이싱

2. 아래의 행렬에서 배열 [[11, 12], [17, 18]] 을 슬라이싱

3. 아래의 행렬에서 배열 [3, 9, 15, 21] 을 슬라이싱

In [113]:
m = np.arange(1, 25).reshape(4, 2, 3)

In [115]:
m

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [117]:
# [8, 14] 를 슬라이싱
m[1:3, 0, 1]

array([ 8, 14])

In [119]:
# [[11, 12], [17, 18]] 을 슬라이싱
m[1:3, 1, 1:]

array([[11, 12],
       [17, 18]])

In [121]:
# [3, 9, 15, 21] 을 슬라이싱
m[:, 0, 2]

array([ 3,  9, 15, 21])

# **파이썬 리스트와 넘파이 배열의 차이**

- 넘파이 배열은 배열끼리 연산이 가능하지만 파이썬 리스트는 값의 추가만 가능
- 넘파이 배열은 숫자와의 연산도 가능하지만 파이썬 리스트는 불가능
    - 파이썬 리스트 : 리스트 요소를 반복하는 것은 가능
- 사용 용도
    - 파이썬 리스트는 값을 추가하거나 제거하는 일에 사용
    - 넘파이 배열은 수치 계산이 많고 복잡하거나 다차원배열이 필요할 때 사용

## 전치 연산(transpose)

- 2차원 배열의 행과 열을 바꾸는 연산

In [125]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [127]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
arr.shape

(2, 3)

In [131]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [133]:
arr.T.shape

(3, 2)

In [135]:
arr.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## 배열 크기 변형

In [138]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [140]:
arr2 = arr1.reshape(3, 4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 사용하는 원소의 수가 정해져 있기 때문에 reshape의 형태 원소 중 하나는 -1로 대체할 수 있음

In [143]:
arr1.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
arr1.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [147]:
arr1.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

# **넘파이 함수의 특징**

- 벡터화 연산
    - 벡터와 행렬의 연산은 구성하는 원소별로 처리하는 것이 보통
    - 동일한 인덱스의 원소끼리 계산을 처리하는 것을 벡터화 연산이라고 함
- 유니버설 함수(universal function)
    - 벡터화 연산을 지원하는 특별한 함수를 유니버설 함수라고 함

In [150]:
# 일반 파이썬 함수의 타입 확인
def test():
    pass

In [152]:
type(test)

function

In [154]:
# 유니버설 함수 확인
type(np.add)

numpy.ufunc

In [156]:
# 넘파이 모듈에는 유니버설 함수도 있고 일반 함수도 있음
type(np.sort)

numpy._ArrayFunctionDispatcher

In [158]:
list2d + list2d

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [160]:
np.add(list2d, list2d)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## 벡터화 연산

### - 벡터화 연산이 필요한 이유

- data 리스트 내의 각 값에 2를 곱해야 하는 경우

In [164]:
# 리스트를 통한 풀이
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [166]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [168]:
ans = []

for i in data:
    ans.append(i * 2)

ans

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [170]:
# 넘파이를 통한 풀이
data = np.array(data)

In [172]:
data * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### : 넘파이 벡터화 연산

- 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됨

In [175]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [177]:
2 * a + b

array([12, 24, 36])

In [179]:
a == 2

array([False,  True, False])

In [181]:
[1, 2, 3] == 2

False

In [183]:
b > 10

array([False,  True,  True])

In [185]:
(a == 2) & (b > 10)

array([False,  True, False])

In [187]:
a[a == 2]

array([2])

In [189]:
b[b > 10]

array([20, 30])

- 배열끼리의 연산

In [192]:
arr1 = np.arange(6, 10)
arr1

array([6, 7, 8, 9])

In [194]:
arr2 = np.arange(10, 14)
arr2

array([10, 11, 12, 13])

In [196]:
# 두 개의 다차원 배열을 곱하면 동일한 인덱스의 원소끼리 곱셈한 결과인 배열이 반환됨
arr1 * arr2

array([ 60,  77,  96, 117])

In [198]:
# arr1에 차원 추가
new_arr1 = arr1.reshape(-1, 1)
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [200]:
new_arr1.shape

(4, 1)

In [202]:
# arr2에 차원 추가
new_arr2 = arr2.reshape(1, -1)
new_arr2

array([[10, 11, 12, 13]])

In [204]:
new_arr2.shape

(1, 4)

In [206]:
# 행렬 요소별 곱셈 연산
new_arr1 * new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [208]:
# 행렬곱 연산
new_arr1 @ new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [210]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [212]:
# * 연산자는 요소별 곱셈을 수행
result = a * b
result

array([[ 5, 12],
       [21, 32]])

In [214]:
# @ 연산자는 행렬곱을 수행
a @ b

array([[19, 22],
       [43, 50]])

## 브로드캐스팅(broadcasting)

- 배열끼리 연산을 하기 위해서는 두 배열의 크기가 같아야 함
- 서로 다른 크기를 가진 배열의 사칙 연산을 하는 경우 넘파이에서는 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞춤

In [217]:
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [219]:
new_arr2

array([[10, 11, 12, 13]])

In [221]:
new_arr1 + new_arr2

array([[16, 17, 18, 19],
       [17, 18, 19, 20],
       [18, 19, 20, 21],
       [19, 20, 21, 22]])

#### 문제

1. 아래의 배열에서 3의 배수를 찾기

2. 아래의 배열에서 4로 나누면 1이 남는 수를 찾기

3. 아래의 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾기

In [224]:
x = np.arange(1, 21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [226]:
# 1. 3의 배수를 찾기
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [228]:
# 2. 4로 나누면 1이 남는 수를 찾기
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [230]:
# 3. 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾기
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

## 축에 따른 연산

- 동일한 축에 있는 원소들을 계산하기 위해서 필요함

### - 1차원배열

In [234]:
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [236]:
# 합계
np.sum(arr1)

10

In [238]:
arr1.sum()

10

In [240]:
# 최댓값
arr1.max()

4

In [242]:
np.max(arr1)

4

In [244]:
# 최솟값
arr1.min()

1

In [246]:
np.min(arr1)

1

In [248]:
# 최솟값의 위치
arr1.argmin()

0

In [250]:
np.argmin(arr1)

0

In [252]:
# 최댓값의 위치
arr1.argmax()

3

In [254]:
np.argmax(arr1)

3

In [256]:
# 평균
arr1.mean()

2.5

In [258]:
np.mean(arr1)

2.5

In [260]:
# 중앙값
np.median(arr1)

2.5

### - 2차원배열

In [263]:
arr2 = arr1.reshape(2, 2)
arr2

array([[1, 2],
       [3, 4]])

In [265]:
# 모든 원소를 더한 합
np.sum(arr2)

10

In [267]:
# 수직방향으로 같은 열에 속한 원소만 합산
np.sum(arr2, axis = 0)

array([4, 6])

In [269]:
# 수평방향으로 같은 행에 속한 원소만 합산
np.sum(arr2, axis = 1)

array([3, 7])

In [271]:
arr3 = np.random.randint(0, 3, size = (2, 3))
arr3

array([[0, 0, 0],
       [2, 1, 1]])

In [273]:
np.sum(arr3, axis = 0)

array([2, 1, 1])

In [275]:
arr3.sum(axis = 0)

array([2, 1, 1])

In [277]:
np.sum(arr3, axis = 1)

array([0, 4])

### - 3차원배열

In [280]:
arr4 = np.arange(1, 9).reshape(2, 2, 2)
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [282]:
# 모든 원소를 더한 합
np.sum(arr4)

36

In [284]:
# 두 개의 행렬의 동일한 인덱스의 원소를 합한 값
np.sum(arr4, axis = 0)

array([[ 6,  8],
       [10, 12]])

In [286]:
# 각 2차원 배열의 열의 합
np.sum(arr4, axis = 1)

array([[ 4,  6],
       [12, 14]])

In [288]:
# 각 2차원 배열의 행의 합
np.sum(arr4, axis = 2)

array([[ 3,  7],
       [11, 15]])

In [290]:
np.sum(arr4, axis = (0, 1))

array([16, 20])

In [292]:
np.sum(arr4, axis = (0, 2))

array([14, 22])

In [294]:
np.sum(arr4, axis = (1, 2))

array([10, 26])

In [296]:
arr5 = np.random.randint(0, 3, size = (2, 3, 4))
arr5

array([[[0, 0, 1, 2],
        [0, 2, 2, 0],
        [2, 1, 0, 1]],

       [[2, 1, 2, 2],
        [1, 1, 2, 0],
        [2, 0, 2, 2]]])

In [298]:
np.sum(arr5, axis = 0)

array([[2, 1, 3, 4],
       [1, 3, 4, 0],
       [4, 1, 2, 3]])

In [300]:
np.sum(arr5, axis = 1)

array([[2, 3, 3, 3],
       [5, 2, 6, 4]])

In [302]:
np.sum(arr5, axis = 2)

array([[3, 4, 4],
       [7, 4, 6]])

In [304]:
np.sum(arr5, axis = (0, 1))

array([7, 5, 9, 7])

In [306]:
np.sum(arr5, axis = (0, 2))

array([10,  8, 10])

In [308]:
np.sum(arr5, axis = (1, 2))

array([11, 17])

#### 문제

1. 전체의 최댓값

2. 각 행의 합

3. 각 행의 최댓값

4. 각 열의 평균

5. 각 열의 최솟값

In [311]:
x = np.random.random((5, 6))
x

array([[0.62538869, 0.01697361, 0.11159269, 0.44685675, 0.0754621 ,
        0.86123441],
       [0.14887684, 0.52448001, 0.48376299, 0.48414494, 0.63331116,
        0.92341959],
       [0.25671767, 0.25035652, 0.94422624, 0.35864373, 0.71148244,
        0.52995829],
       [0.76237111, 0.903438  , 0.3723574 , 0.21486335, 0.28436462,
        0.33622404],
       [0.45874833, 0.73335727, 0.86351045, 0.04607716, 0.23986474,
        0.18872122]])

In [313]:
# 1. 전체의 최댓값
x.max()

0.9442262386780322

In [315]:
# 2. 각 행의 합
x.sum(axis = 1)

array([2.13750825, 3.19799554, 3.0513849 , 2.87361851, 2.53027916])

In [317]:
# 3. 각 행의 최댓값
x.max(axis = 1)

array([0.86123441, 0.92341959, 0.94422624, 0.903438  , 0.86351045])

In [319]:
# 4. 각 열의 평균
x.mean(axis = 0)

array([0.45042053, 0.48572108, 0.55508995, 0.31011719, 0.38889701,
       0.56791151])

In [321]:
# 5. 각 열의 최솟값
x.min(axis = 0)

array([0.14887684, 0.01697361, 0.11159269, 0.04607716, 0.0754621 ,
       0.18872122])

1. 각 2차원 배열에서의 최댓값

2. 각 2차원 배열에서의 행의 합

3. 각 2차원 배열에서의 각 행의 최댓값

4. 전체 열의 평균

5. 각 2차원 배열에서의 열의 평균

6. 각 2차원 배열에서의 각 열의 최솟값

In [324]:
data_3d = np.random.random((3, 5, 6))
data_3d

array([[[0.60770241, 0.54985137, 0.20495353, 0.21778075, 0.48675115,
         0.05564722],
        [0.14937138, 0.63934379, 0.93706884, 0.03544604, 0.86173847,
         0.41926797],
        [0.73848244, 0.67062547, 0.659019  , 0.63175521, 0.02483982,
         0.188027  ],
        [0.64024774, 0.02695244, 0.30882419, 0.41427607, 0.47745453,
         0.49828807],
        [0.75010155, 0.24497341, 0.59663501, 0.86699083, 0.89521478,
         0.32445754]],

       [[0.84271768, 0.32114295, 0.40792696, 0.94427178, 0.85486151,
         0.06893021],
        [0.71502929, 0.9963821 , 0.1591308 , 0.9709803 , 0.00563513,
         0.827785  ],
        [0.19136573, 0.79833515, 0.97716541, 0.94829894, 0.93822331,
         0.43509378],
        [0.70380482, 0.72672665, 0.4478136 , 0.2381245 , 0.67505186,
         0.70998841],
        [0.79396911, 0.66169554, 0.52569985, 0.80312523, 0.39927971,
         0.5690429 ]],

       [[0.63953258, 0.42463409, 0.01736008, 0.84978241, 0.66180107,
         0.045439

In [326]:
# 1. 각 2차원 배열에서의 최댓값
data_3d.max(axis = (1, 2))

array([0.93706884, 0.9963821 , 0.97693335])

In [328]:
# 2. 각 2차원 배열에서의 행의 합
data_3d.sum(axis = 2)

array([[2.12268641, 3.04223649, 2.91274894, 2.36604305, 3.67837313],
       [3.43985109, 3.67494263, 4.28848232, 3.50150985, 3.75281235],
       [2.6385495 , 2.8538149 , 3.9694792 , 2.19321134, 2.19081706]])

In [330]:
# 3. 각 2차원 배열에서의 각 행의 최댓값
data_3d.max(axis = 2)

array([[0.60770241, 0.93706884, 0.73848244, 0.64024774, 0.89521478],
       [0.94427178, 0.9963821 , 0.97716541, 0.72672665, 0.80312523],
       [0.84978241, 0.97693335, 0.95346816, 0.7942019 , 0.59554797]])

In [332]:
# 4. 전체 열의 평균
data_3d.mean(axis = (0, 1))

array([0.59250887, 0.5064909 , 0.46342927, 0.64263844, 0.52299121,
       0.38031186])

In [334]:
# 5. 각 2차원 배열에서의 열의 평균
data_3d.mean(axis = 1)

array([[0.5771811 , 0.4263493 , 0.54130011, 0.43324978, 0.54919975,
        0.29713756],
       [0.64937733, 0.70085648, 0.50354732, 0.78096015, 0.57461031,
        0.52216806],
       [0.55096818, 0.39226692, 0.34544038, 0.71370539, 0.44516358,
        0.32162995]])

In [336]:
# 6. 각 2차원 배열에서의 각 열의 최솟값
data_3d.min(axis = 1)

array([[0.14937138, 0.02695244, 0.20495353, 0.03544604, 0.02483982,
        0.05564722],
       [0.19136573, 0.32114295, 0.1591308 , 0.2381245 , 0.00563513,
        0.06893021],
       [0.2725731 , 0.05352062, 0.01736008, 0.37552654, 0.15225947,
        0.04543927]])

# **Inf와 nan**

- 넘파이에서는 무한대를 표현하기 위한 np.inf 와 정의할 수 없는 숫자를 나타내는 np.nan 이 있음

In [339]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\user\AppData\Local\Temp\ipykernel_9700\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\user\AppData\Local\Temp\ipykernel_9700\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])