In [1]:
import numpy as np

# 넘파이 배열의 구조

- 넘파이 모듈의 기본 배열은 ndarray(n-dimension array, 다차원배열)

## 1) 다차원배열 생성

In [5]:
# 리스트를 다차원배열로 변환
# np.array() : 다차원 배열을 만드는 함수
li = [1, 2, 3, 4]
li_arr = np.array(li)

In [7]:
li_arr

array([1, 2, 3, 4])

In [9]:
type(li_arr)

numpy.ndarray

In [11]:
# 튜플을 다차원 배열로 변환
tu = (1, 2, 3, 4)
tu_arr = np.array(tu)

In [13]:
tu_arr

array([1, 2, 3, 4])

In [15]:
type(tu_arr)

numpy.ndarray

In [17]:
# 다차원배열은 mutable의 특징을 가짐
# 변수를 다른 변수에 복사한 뒤 데이터를 수정하면 모든 변수의 데이터가 수정됨
co_arr = li_arr
id(co_arr), id(li_arr)

(2800293637424, 2800293637424)

In [19]:
co_arr

array([1, 2, 3, 4])

In [21]:
co_arr[0] = 100

In [23]:
co_arr

array([100,   2,   3,   4])

In [25]:
li_arr

array([100,   2,   3,   4])

In [27]:
# 다차원 배열의 값을 복사해서 새로운 배열을 만들면
# 동일한 값을 가진 새로운 배열이 만들어지기 때문에 서로 다른 데이터가 됨
new_arr = np.array(li_arr)

In [29]:
id(new_arr), id(li_arr)

(2798247767152, 2800293637424)

In [31]:
new_arr[0] = 99

In [33]:
new_arr

array([99,  2,  3,  4])

In [35]:
li_arr

array([100,   2,   3,   4])

- 파이썬 리스트는 다양한 자료형을 사용할 수 있지만 넘파이 배열은 같은 자료형만 넣을 수 있음
    - 다차원 배열을 생성할 때 자료형을 지정하지 않으면 내부의 원소를 보고 자동으로 추론해서 만듦

In [38]:
# float 자료형을 지정해서 다차원 배열 생성하기
fl_arr = np.array(li, dtype = float)

In [40]:
fl_arr

array([1., 2., 3., 4.])

In [42]:
fl_arr.dtype

dtype('float64')

### (1) 2차원 배열

- 2개의 축을 가지는 배열(행, 열)
    - 두 개의 1차원 배열이 쌓여서 하나의 2차원 배열이 만들어짐

In [45]:
arr2d = np.array([[1, 2, 3],[4, 5, 6]])

In [47]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
# 각 축의 원소의 개수
arr2d.shape

(2, 3)

In [51]:
# 축의 개수
arr2d.ndim

2

In [53]:
arr2d.dtype

dtype('int32')

In [55]:
# 다차원 배열을 1차원 배열로 조회
arr2d.flatten()

array([1, 2, 3, 4, 5, 6])

In [57]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

## 2) 다차원배열에서 원소 조회하기

In [61]:
li_arr

array([100,   2,   3,   4])

In [63]:
li

[1, 2, 3, 4]

In [65]:
li[0]

1

In [67]:
li_arr[0]

100

In [69]:
# 배열을 리스트로 변환
list2d = arr2d.tolist()

In [71]:
list2d

[[1, 2, 3], [4, 5, 6]]

In [73]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
# 리스트는 정수만 이용해서 원소 조회 가능
# 따라서 리스트 내 리스트의 원소를 조회할 때는 인덱싱을 두 번 사용해야함
list2d[0][1]

2

In [77]:
list2d[0, 1]

TypeError: list indices must be integers or slices, not tuple

In [79]:
# 다차원 배열은 행과 열의 인덱스를 튜플로 조회할 수 있음
arr2d[0, 1]

2

In [81]:
arr2d[0][1]

2

In [83]:
# 슬라이싱
arr1 = np.array([[0, 1, 2, 3],
                 [4, 5, 6, 7]])

In [85]:
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [87]:
# 첫 번째 행 전체
arr1[0, :]

array([0, 1, 2, 3])

In [89]:
# 두 번째 열 전체
arr1[:, 1]

array([1, 5])

In [91]:
# 두 번째 행의 두 번째 열부터 끝열까지
arr1[1, 1:]

array([5, 6, 7])

In [93]:
# 각 행의 두 번째 열까지
arr1[:, :2]

array([[0, 1],
       [4, 5]])

### 연습문제

1. 아래의 행렬에서 값 7을 인덱싱
2. 아래의 행렬에서 값 14를 인덱싱
3. 아래의 행렬에서 배열 [6, 7]을 슬라이싱
4. 아래의 행렬에서 배열 [7, 12]를 슬라이싱
5. 아래의 행렬에서 배열[[3, 4], [8, 9]]를 슬라이싱

In [97]:
m = np.arange(15).reshape(3, 5)

In [99]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [101]:
# 1. 값 7을 인덱싱
m[1, 2]

7

In [103]:
# 2. 값 14를 인덱싱
# m[2, 4]
m[-1, -1]

14

In [105]:
# 3. 배열 [6, 7]을 슬라이싱
m[1, 1:3]

array([6, 7])

In [107]:
# 4. 배열 [7, 12]를 슬라이싱
m[1:, 2]

array([ 7, 12])

In [109]:
# 5. 배열[[3, 4], [8, 9]]를 슬라이싱
m[:2, 3:]

array([[3, 4],
       [8, 9]])

## 3) 파이썬 리스트와 넘파이 배열의 차이

- 넘파이 배열은 배열끼리 연산이 가능하지만 파이썬 리스트는 값의 추가만 가능
- 넘파이 배열은 숫자와의 연산도 가능하지만 파이썬 리스트는 불가능
  - 파이썬 리스트 : 요소를 반복하는 것은 가능
- 사용 용도
  - 파이썬 리스트는 값을 추가하거나 제거하는 일에 사용
  - 넘파이 배열은 수치 계산이 많고 복잡하거나 다차원배열이 필요할 때 사용

# 전치 연산(transpose)

- 2차원 배열의 행과 열을 바꾸는 연산

In [114]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [116]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
arr.shape

(2, 3)

In [120]:
# 전치
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [122]:
arr.T.shape

(3, 2)

# 배열 크기 변형

In [125]:
arr1 = np.arange(12)

In [127]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [129]:
# arr1의 shape를 (3, 4)로 변형
arr2 = arr1.reshape(3, 4)

In [131]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 사용하는 원소의 수가 정해져 있기 때문에 reshape의 형태 원소 중 하나는 -1로 대체할 수 있음

In [134]:
arr1.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
arr1.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [138]:
arr1.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [140]:
arr1.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

# 넘파이 함수의 특징

- 벡터화 연산
  - 벡터와 행렬의 연산은 구성하는 원소별로 처리하는 것이 보통
  - 동일한 인덱스의 원소끼리 계산을 처리하는 것을 벡터화 연산이라고 함
- 유니버설 함수(universal function)
  - 벡터화 연산을 지원하는 특별한 함수를 유니버설 함수라고 함

In [143]:
# 일반 파이썬 함수의 타입 확인
def test() :
    pass

type(test)

function

In [145]:
# 유니버셜 함수 확인
type(np.add)

numpy.ufunc

In [147]:
# 넘파이 모듈에는 유니버셜 함수도 있고 일반 함수도 있음
type(np.sort)

numpy._ArrayFunctionDispatcher

In [149]:
list2d + list2d

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [151]:
np.add(list2d, list2d)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## 1) 벡터화 연산

- 벡터화 연산이 필요한 이유
    - 예) data 리스트 내의 각 값에 2를 곱해야 하는 경우

In [154]:
# 리스트를 통한 풀이
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [156]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [158]:
ans = []

for i in data :
    ans.append(i * 2)

ans

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [160]:
# 넘파이를 통한 풀이
data = np.array(data)

data * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### (1) 넘파이 벡터화 연산

- 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됨

In [163]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [165]:
2 * a + b

array([12, 24, 36])

In [167]:
a == 2

array([False,  True, False])

In [169]:
[1, 2, 3] == 2

False

In [171]:
b > 10

array([False,  True,  True])

In [173]:
(a == 2) & (b > 10)

array([False,  True, False])

In [175]:
a[a == 2]

array([2])

- 배열끼리의 연산

In [178]:
arr1 = np.arange(6, 10)
arr1

array([6, 7, 8, 9])

In [180]:
arr2 = np.arange(10, 14)
arr2

array([10, 11, 12, 13])

In [182]:
# 두 개의 다차원 배열을 곱하면 동일한 인덱스의 원소끼리 곱셈한 결과인 1차원 배열이 반환됨
arr1 * arr2

array([ 60,  77,  96, 117])

In [184]:
# arr1에 수직축 추가
new_arr1 = arr1.reshape(-1, 1)
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [186]:
new_arr1.shape

(4, 1)

In [188]:
# arr2에 수평축 추가
new_arr2 = arr2.reshape(1, -1)
new_arr2

array([[10, 11, 12, 13]])

In [190]:
new_arr2.shape

(1, 4)

In [192]:
# 2차원 배열의 곱하기 연산
new_arr1 * new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [194]:
# 행렬곱 연산
new_arr1 @ new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [196]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# * 연산자는 요소별 곱셈을 수행
result = a * b
result

array([[ 5, 12],
       [21, 32]])

In [198]:
# @ 연산자는 행렬곱셈을 수행
a @ b

array([[19, 22],
       [43, 50]])

## 2) 브로드캐스팅(broadcasting)

- 배열끼리 연산을 하기 위해서는 두 배열의 크기가 같아야함
- 서로 다른 크기를 가진 배열의 사칙 연산을 하는 경우 넘파이에서는 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞춤

In [203]:
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [205]:
new_arr2

array([[10, 11, 12, 13]])

In [207]:
new_arr1 + new_arr2

array([[16, 17, 18, 19],
       [17, 18, 19, 20],
       [18, 19, 20, 21],
       [19, 20, 21, 22]])

### 연습문제

1. 아래의 배열에서 3의 배수를 찾기
2. 아래의 배열에서 4로 나누면 1이 남는 수를 찾기
3. 아래의 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾기

In [210]:
x = np.arange(1, 21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [212]:
# 1. 3의 배수를 찾기
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [214]:
# 2. 4로 나누면 1이 남는 수를 찾기
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [216]:
# 3. 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾기
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])