In [1]:
import numpy as np

# 넘파이 배열의 구조

- 넘파이 모듈의 기본 배열은 ndarray(n-dimension array, 다차원배열)

## 1) 다차원배열 생성

In [5]:
# 리스트를 다차원배열로 변환
# np.array() : 다차원 배열을 만드는 함수
li = [1, 2, 3, 4]
li_arr = np.array(li)

In [7]:
li_arr

array([1, 2, 3, 4])

In [9]:
type(li_arr)

numpy.ndarray

In [11]:
# 튜플을 다차원 배열로 변환
tu = (1, 2, 3, 4)
tu_arr = np.array(tu)

In [13]:
tu_arr

array([1, 2, 3, 4])

In [15]:
type(tu_arr)

numpy.ndarray

In [17]:
# 다차원배열은 mutable의 특징을 가짐
# 변수를 다른 변수에 복사한 뒤 데이터를 수정하면 모든 변수의 데이터가 수정됨
co_arr = li_arr
id(co_arr), id(li_arr)

(2800293637424, 2800293637424)

In [19]:
co_arr

array([1, 2, 3, 4])

In [21]:
co_arr[0] = 100

In [23]:
co_arr

array([100,   2,   3,   4])

In [25]:
li_arr

array([100,   2,   3,   4])

In [27]:
# 다차원 배열의 값을 복사해서 새로운 배열을 만들면
# 동일한 값을 가진 새로운 배열이 만들어지기 때문에 서로 다른 데이터가 됨
new_arr = np.array(li_arr)

In [29]:
id(new_arr), id(li_arr)

(2798247767152, 2800293637424)

In [31]:
new_arr[0] = 99

In [33]:
new_arr

array([99,  2,  3,  4])

In [35]:
li_arr

array([100,   2,   3,   4])

- 파이썬 리스트는 다양한 자료형을 사용할 수 있지만 넘파이 배열은 같은 자료형만 넣을 수 있음
    - 다차원 배열을 생성할 때 자료형을 지정하지 않으면 내부의 원소를 보고 자동으로 추론해서 만듦

In [38]:
# float 자료형을 지정해서 다차원 배열 생성하기
fl_arr = np.array(li, dtype = float)

In [40]:
fl_arr

array([1., 2., 3., 4.])

In [42]:
fl_arr.dtype

dtype('float64')

### (1) 2차원 배열

- 2개의 축을 가지는 배열(행, 열)
    - 두 개의 1차원 배열이 쌓여서 하나의 2차원 배열이 만들어짐

In [45]:
arr2d = np.array([[1, 2, 3],[4, 5, 6]])

In [47]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
# 각 축의 원소의 개수
arr2d.shape

(2, 3)

In [51]:
# 축의 개수
arr2d.ndim

2

In [53]:
arr2d.dtype

dtype('int32')

In [55]:
# 다차원 배열을 1차원 배열로 조회
arr2d.flatten()

array([1, 2, 3, 4, 5, 6])

In [57]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

## 2) 다차원배열에서 원소 조회하기

In [61]:
li_arr

array([100,   2,   3,   4])

In [63]:
li

[1, 2, 3, 4]

In [65]:
li[0]

1

In [67]:
li_arr[0]

100

In [69]:
# 배열을 리스트로 변환
list2d = arr2d.tolist()

In [71]:
list2d

[[1, 2, 3], [4, 5, 6]]

In [73]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
# 리스트는 정수만 이용해서 원소 조회 가능
# 따라서 리스트 내 리스트의 원소를 조회할 때는 인덱싱을 두 번 사용해야함
list2d[0][1]

2

In [77]:
list2d[0, 1]

TypeError: list indices must be integers or slices, not tuple

In [79]:
# 다차원 배열은 행과 열의 인덱스를 튜플로 조회할 수 있음
arr2d[0, 1]

2

In [81]:
arr2d[0][1]

2

In [83]:
# 슬라이싱
arr1 = np.array([[0, 1, 2, 3],
                 [4, 5, 6, 7]])

In [85]:
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [87]:
# 첫 번째 행 전체
arr1[0, :]

array([0, 1, 2, 3])

In [89]:
# 두 번째 열 전체
arr1[:, 1]

array([1, 5])

In [91]:
# 두 번째 행의 두 번째 열부터 끝열까지
arr1[1, 1:]

array([5, 6, 7])

In [93]:
# 각 행의 두 번째 열까지
arr1[:, :2]

array([[0, 1],
       [4, 5]])

### 연습문제

1. 아래의 행렬에서 값 7을 인덱싱
2. 아래의 행렬에서 값 14를 인덱싱
3. 아래의 행렬에서 배열 [6, 7]을 슬라이싱
4. 아래의 행렬에서 배열 [7, 12]를 슬라이싱
5. 아래의 행렬에서 배열[[3, 4], [8, 9]]를 슬라이싱

In [97]:
m = np.arange(15).reshape(3, 5)

In [99]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [101]:
# 1. 값 7을 인덱싱
m[1, 2]

7

In [103]:
# 2. 값 14를 인덱싱
# m[2, 4]
m[-1, -1]

14

In [105]:
# 3. 배열 [6, 7]을 슬라이싱
m[1, 1:3]

array([6, 7])

In [107]:
# 4. 배열 [7, 12]를 슬라이싱
m[1:, 2]

array([ 7, 12])

In [109]:
# 5. 배열[[3, 4], [8, 9]]를 슬라이싱
m[:2, 3:]

array([[3, 4],
       [8, 9]])

## 3) 파이썬 리스트와 넘파이 배열의 차이

- 넘파이 배열은 배열끼리 연산이 가능하지만 파이썬 리스트는 값의 추가만 가능
- 넘파이 배열은 숫자와의 연산도 가능하지만 파이썬 리스트는 불가능
  - 파이썬 리스트 : 요소를 반복하는 것은 가능
- 사용 용도
  - 파이썬 리스트는 값을 추가하거나 제거하는 일에 사용
  - 넘파이 배열은 수치 계산이 많고 복잡하거나 다차원배열이 필요할 때 사용

# 전치 연산(transpose)

- 2차원 배열의 행과 열을 바꾸는 연산

In [114]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [116]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
arr.shape

(2, 3)

In [120]:
# 전치
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [122]:
arr.T.shape

(3, 2)

# 배열 크기 변형

In [125]:
arr1 = np.arange(12)

In [127]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [129]:
# arr1의 shape를 (3, 4)로 변형
arr2 = arr1.reshape(3, 4)

In [131]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 사용하는 원소의 수가 정해져 있기 때문에 reshape의 형태 원소 중 하나는 -1로 대체할 수 있음

In [134]:
arr1.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
arr1.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [138]:
arr1.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [140]:
arr1.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

# 넘파이 함수의 특징

- 벡터화 연산
  - 벡터와 행렬의 연산은 구성하는 원소별로 처리하는 것이 보통
  - 동일한 인덱스의 원소끼리 계산을 처리하는 것을 벡터화 연산이라고 함
- 유니버설 함수(universal function)
  - 벡터화 연산을 지원하는 특별한 함수를 유니버설 함수라고 함

In [143]:
# 일반 파이썬 함수의 타입 확인
def test() :
    pass

type(test)

function

In [145]:
# 유니버셜 함수 확인
type(np.add)

numpy.ufunc

In [147]:
# 넘파이 모듈에는 유니버셜 함수도 있고 일반 함수도 있음
type(np.sort)

numpy._ArrayFunctionDispatcher

In [149]:
list2d + list2d

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [151]:
np.add(list2d, list2d)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## 1) 벡터화 연산

- 벡터화 연산이 필요한 이유
    - 예) data 리스트 내의 각 값에 2를 곱해야 하는 경우

In [154]:
# 리스트를 통한 풀이
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [156]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [158]:
ans = []

for i in data :
    ans.append(i * 2)

ans

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [160]:
# 넘파이를 통한 풀이
data = np.array(data)

data * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### (1) 넘파이 벡터화 연산

- 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됨

In [163]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [165]:
2 * a + b

array([12, 24, 36])

In [167]:
a == 2

array([False,  True, False])

In [169]:
[1, 2, 3] == 2

False

In [171]:
b > 10

array([False,  True,  True])

In [173]:
(a == 2) & (b > 10)

array([False,  True, False])

In [175]:
a[a == 2]

array([2])

- 배열끼리의 연산

In [178]:
arr1 = np.arange(6, 10)
arr1

array([6, 7, 8, 9])

In [180]:
arr2 = np.arange(10, 14)
arr2

array([10, 11, 12, 13])

In [182]:
# 두 개의 다차원 배열을 곱하면 동일한 인덱스의 원소끼리 곱셈한 결과인 1차원 배열이 반환됨
arr1 * arr2

array([ 60,  77,  96, 117])

In [184]:
# arr1에 수직축 추가
new_arr1 = arr1.reshape(-1, 1)
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [186]:
new_arr1.shape

(4, 1)

In [188]:
# arr2에 수평축 추가
new_arr2 = arr2.reshape(1, -1)
new_arr2

array([[10, 11, 12, 13]])

In [190]:
new_arr2.shape

(1, 4)

In [192]:
# 2차원 배열의 곱하기 연산
new_arr1 * new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [194]:
# 행렬곱 연산
new_arr1 @ new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [196]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# * 연산자는 요소별 곱셈을 수행
result = a * b
result

array([[ 5, 12],
       [21, 32]])

In [198]:
# @ 연산자는 행렬곱셈을 수행
a @ b

array([[19, 22],
       [43, 50]])

## 2) 브로드캐스팅(broadcasting)

- 배열끼리 연산을 하기 위해서는 두 배열의 크기가 같아야함
- 서로 다른 크기를 가진 배열의 사칙 연산을 하는 경우 넘파이에서는 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞춤

In [203]:
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [205]:
new_arr2

array([[10, 11, 12, 13]])

In [207]:
new_arr1 + new_arr2

array([[16, 17, 18, 19],
       [17, 18, 19, 20],
       [18, 19, 20, 21],
       [19, 20, 21, 22]])

### 연습문제

1. 아래의 배열에서 3의 배수를 찾기
2. 아래의 배열에서 4로 나누면 1이 남는 수를 찾기
3. 아래의 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾기

In [210]:
x = np.arange(1, 21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [212]:
# 1. 3의 배수를 찾기
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [214]:
# 2. 4로 나누면 1이 남는 수를 찾기
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [216]:
# 3. 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾기
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

## 3) 축에 따른 연산

- 동일한 축에 있는 원소들을 계산하기 위해서 필요함

In [278]:
# 1차원 배열
arr1 = np.array([1, 2, 3, 4])

In [297]:
arr1

array([1, 2, 3, 4])

In [299]:
# 합계
np.sum(arr1)

10

In [301]:
arr1.sum()

10

In [303]:
# 최댓값
arr1.max()

4

In [305]:
np.max(arr1)

4

In [307]:
# 최솟값
arr1.min()

1

In [309]:
np.min(arr1)

1

In [311]:
# 최댓값의 위치
arr1.argmax()

3

In [313]:
# 최솟값의 위치
arr1.argmin()

0

In [315]:
# 평균
arr1.mean()

2.5

In [317]:
# 중앙값
np.median(arr1)

2.5

In [319]:
# 2차원배열
arr2 = arr1.reshape(2, 2)

In [321]:
arr2

array([[1, 2],
       [3, 4]])

In [323]:
# 모든 원소를 더한 합
np.sum(arr2)

10

In [325]:
# 수직 방향으로 같은 열에 속한 원소만 합산
np.sum(arr2, axis = 0)

array([4, 6])

In [327]:
# 수평 방향으로 같은 열에 속한 원소만 합산
np.sum(arr2, axis = 1)

array([3, 7])

In [329]:
arr3 = np.random.randint(0, 10, (2, 3))

In [331]:
arr3

array([[2, 2, 1],
       [1, 5, 1]])

In [347]:
arr3.shape

(2, 3)

In [349]:
np.sum(arr3)

12

In [351]:
np.sum(arr3, axis = 0)

array([3, 7, 2])

In [353]:
np.sum(arr3, axis = 1)

array([5, 7])

In [355]:
# 3차원배열
arr4 = np.arange(1, 9)

In [357]:
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [359]:
arr5 = arr4.reshape(2, 2, 2)

In [361]:
arr5

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [363]:
# 모든 원소를 더한 합
np.sum(arr5)

36

In [365]:
# 두 개의 행렬의 동일한 인덱스의 원소를 합한 값
np.sum(arr5, axis = 0)

array([[ 6,  8],
       [10, 12]])

In [367]:
# 각 2차원 배열의 0번축의 합
np.sum(arr5, axis = 1)

array([[ 4,  6],
       [12, 14]])

In [369]:
# 각 2차원 배열의 1번축의 합
np.sum(arr5, axis = 2)

array([[ 3,  7],
       [11, 15]])

In [371]:
np.sum(arr5, axis = (0, 1))

array([16, 20])

In [373]:
np.sum(arr5, axis = (0, 2))

array([14, 22])

In [375]:
np.sum(arr5, axis = (1, 2))

array([10, 26])

In [393]:
arr6 = np.random.randint(0, 10, (2, 3, 4))

In [395]:
arr6

array([[[9, 3, 0, 4],
        [2, 0, 5, 8],
        [8, 6, 2, 0]],

       [[8, 5, 5, 1],
        [7, 8, 4, 8],
        [3, 9, 0, 1]]])

In [397]:
arr6.shape

(2, 3, 4)

In [399]:
np.sum(arr6, axis = 0)

array([[17,  8,  5,  5],
       [ 9,  8,  9, 16],
       [11, 15,  2,  1]])

In [401]:
np.sum(arr6, axis = 1)

array([[19,  9,  7, 12],
       [18, 22,  9, 10]])

In [403]:
np.sum(arr6, axis = 2)

array([[16, 15, 16],
       [19, 27, 13]])

In [405]:
np.sum(arr6, axis = (0, 1))

array([37, 31, 16, 22])

In [407]:
np.sum(arr6, axis = (0, 2))

array([35, 42, 29])

In [409]:
np.sum(arr6, axis = (1, 2))

array([47, 59])

### 연습문제

- 실수로 이루어진 5 * 6 형태의 행렬에서 다음의 값을 구하기

1. 전체의 최댓값
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최솟값

In [413]:
x = np.random.random((5, 6))

In [415]:
x

array([[0.41684002, 0.09014165, 0.66657512, 0.58228203, 0.85839937,
        0.76828497],
       [0.83732917, 0.66341943, 0.3994519 , 0.62590432, 0.19337894,
        0.58275658],
       [0.99943234, 0.63931451, 0.2263342 , 0.1599738 , 0.27190848,
        0.97836395],
       [0.87655531, 0.63161616, 0.4516948 , 0.3025259 , 0.44872418,
        0.48269331],
       [0.2873968 , 0.64859413, 0.41957275, 0.2537321 , 0.67118885,
        0.84699794]])

In [417]:
# 1. 전체의 최댓값
np.max(x)

0.9994323431241966

In [419]:
# 2. 각 행의 합
np.sum(x, axis = 1)

array([3.38252316, 3.30224034, 3.27532729, 3.19380965, 3.12748257])

In [421]:
# 3. 각 행의 최댓값
np.max(x, axis = 1)

array([0.85839937, 0.83732917, 0.99943234, 0.87655531, 0.84699794])

In [423]:
# 4. 각 열의 평균
np.mean(x, axis = 0)

array([0.68351073, 0.53461718, 0.43272575, 0.38488363, 0.48871996,
       0.73181935])

In [425]:
# 5. 각 열의 최솟값
np.min(x, axis = 0)

array([0.2873968 , 0.09014165, 0.2263342 , 0.1599738 , 0.19337894,
       0.48269331])

# Inf와 nan

- 넘파이에서는 무한대를 표현하기 위한 np.inf와 정의할 수 없는 숫자를 나타내는 np.nan이 있음

In [444]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 1])

C:\Users\user\AppData\Local\Temp\ipykernel_10584\4160345212.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 1])


array([  0.,  inf, -inf,   0.])

# 스칼라와 벡터

- 벡터와 행렬은 특정 텐서(tensor)를 부르는 이름
- 텐서의 이름을 부여하는 원칙은 차원인 축(axis)을 기준으로 지정
  - 텐서가 0차원인 경우(축이 없는 경우) : 스칼라(scalar)
  - 1차원인 경우 : 벡터(vector)
  - 2차원인 경우 : 행렬(matrix)
  - 3차원인 경우 : 큐브(cube) 또는 3차원 텐서
  - 더 차원이 높은 경우는 차원을 기준으로 n차원 텐서라고 부름 

## 1) 스칼라

- 0차원 배열
- 크기를 표현
- 가장 기본적인 값
- 수학에서 배운 정수나 실수는 하나의 물리량인 크기를 표현하는데, 이 값을 스칼라 라고 함

In [447]:
scalar_arr = np.array(43)

In [449]:
# array에서 스칼라는 대괄호 없이 숫자만 표시
# 대괄호는 벡터(1차원 배열)부터 사용
scalar_arr

array(43)

In [451]:
type(scalar_arr)

numpy.ndarray

In [453]:
# 스칼라는 0차원
scalar_arr.ndim

0

In [455]:
# 축이 없기 때문에 빈 튜플
scalar_arr.shape

()

In [457]:
# array로 스칼라를 만들어도 dtype을 가짐
scalar_arr.dtype

dtype('int32')

## 2) 벡터

- 1차원 배열

In [460]:
vector = np.array([43])

In [462]:
vector

array([43])

In [464]:
type(vector)

numpy.ndarray

In [486]:
# 1차원 배열
vector.ndim

1

In [488]:
vector.shape

(1,)

## 3) 배열 생성 함수

### (1) zeros

- 크기가 정해져 있고 모든 값이 0인 배열 생성
- 인수로는 배열의 크기를 전달

In [494]:
# 1차원 배열
zero_arr = np.zeros(5)
zero_arr

array([0., 0., 0., 0., 0.])

In [496]:
# 2차원 배열
zero_arr2 = np.zeros((2, 3))
zero_arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

- dtype 인수를 명시하면 해당 자료형 원소 배열을 생성

In [499]:
zero_arr3 = np.zeros((5, 2), dtype = int)
zero_arr3

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

### (2) ones

- 모든 값이 1인 배열 생성

In [502]:
one_arr = np.ones((2, 3, 4), dtype = int)

In [504]:
one_arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

### (3) zeros_like, ones_like

- 다른 배열과 같은 크기의 배열을 생성

In [507]:
zero_arr4 = np.zeros_like(one_arr)

In [509]:
zero_arr4

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [511]:
one_arr2 = np.ones_like(zero_arr3)

In [513]:
one_arr2

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [515]:
one_arr2 = np.ones_like(zero_arr2)

In [517]:
one_arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

### (4) arange

- 파이썬의 range와 유사한 함수
- range와 같이 시작점, 종료점, 증감값을 인자로 전달
  - 종료점은 필수

In [532]:
vector = np.arange(10)
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [534]:
vector.dtype

dtype('int32')

- arange는 인자로 실수를 지정할 수 있음. 

In [537]:
range(10.5, 20.5, 0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [539]:
vector1 = np.arange(10.5, 20.5, 0.5)
vector1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [541]:
# 자료형은 float64
vector1.dtype

dtype('float64')

In [543]:
# 1차원 배열을 생성하면서 바로 2차원 배열로 형상 변경
vector2 = np.arange(60).reshape(6, 10)

In [545]:
vector2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [547]:
vector2.shape

(6, 10)

In [549]:
# 1차원 배열을 생성하면서 바로 3차원 배열로 형상 변경
vector3 = np.arange(60).reshape(3, 4, 5)
vector3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

### (5) linspace

- arange와의 차이점
  - 종료점도 포함해서 원소를 생성
  - 세 번째 인자로 간격 대신 원소의 개수를 전달
    - 초기값은 50
  - 기본으로 실수를 가진 원소를 만듦

In [553]:
lin = np.linspace(1, 10, 10)
lin

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [555]:
lin.dtype

dtype('float64')

In [557]:
# 값의 간격을 표시하는 증분(incremental)을 확인할 수 있음
lin2 = np.linspace(1, 2, 10, retstep = True)
lin2

(array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]),
 0.1111111111111111)

In [559]:
# 종료값을 제외할 수도 있음
lin3 = np.linspace(1, 10, 10, endpoint = False, retstep = True)
lin3

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)