# 자료 구조

### 자료구조란?

- 컴퓨터 프로그램 안에서 데이터를 체계적으로 저장하고, 관리하는 방식이다.
- 자료구조는 데이터를 '효율적'으로 저장하고 관리하기 위한 구조화된 방식이다.
- "데이터를 어떻게 구조화 할 것인가"에 대한 고민

### 왜 필요할까?

- 프로그래밍에서 다루는 거의 모든 문제는 "데이터를 처리하는 문제"이다.
- 데이터를 무작정 저장하면, 원하는 정보를 찾는데 시간이 오래걸리거나, 추가/삭제 작업이 복잡해진다.

### 예시

- 고객 정보를 저장하고 검색해야한다.
- 수강 신청 내역을 빠르게 불러와야한다.
- 게임에서 수천 개의 오브젝트를 실시간으로 처리해야한다.
- **데이터를 효율적으로 저장, 탐색, 수정, 삭제하기 위해 자료구조가 반드시 필요하다.**

### 자료구조가 중요한 세가지 이유

1. 속도
    - 좋은 자료구조를 사용하면 프로그램의 실행 속도가 크게 향상된다.
    - 빅오(Big-O) 표기법 : "이 코드(또는 알고리즘)는 얼마나 효율적일까?"를 수학적으로 표현하는 방법
2. 유지보수
3. 현실 문제 해결

### 빅오(Big-O) 표기법



|빅오표기|의미|예시|비유|정확한 의미|
|---|---|---|---|---|
|O(1)|상수시간|리스트[0]|1층 버튼 바로 누르기|바로 접근 가능|
|O(log n)| 로그시간|이진 탐색|몇 층인지 모르지만, 중간부터 시작해서 절반씩 범위 줄이기|절반씩 탐색(이진 탐색 구조)|                           
|O(n)|선형시간|for 반복문 : 데이터 개수에 비례|계단을 하나씩 내려가기|모든 데이터를 다 봐야한다|
|O(n log n)|로그선형|효율적인 정렬|||
|O(n^2)|제곱시간|중첩반복문|건물 사람 전부 만나서 인사|모든 조합 다 탐색|
|O(2^n)|지수시간|피보나치 재귀(비효율적)|||
|O(n!)|팩토리얼 시간|순열 탐색|||

* O(n log n) -> 자주 쓰임 : 정렬 알고리즘 (퀵 정렬, 병합 정렬), 일부 탐색 알고리즘

# 자료구조 1. 배열(array)

- 대표적으로 두가지 : array.array, numpy.array

## 1) array.array

- 기본 제공 배열 모듈
- 같은 자료형만 저장 가능한 1차원 배열
- 메모리를 덜 쓰고, 리스트보다 약간 빠름
- 하지만 기능이 매우 제한적 -> 실무에서는 거의 사용되지 않음
- 저장공간이 제한되어 있음
- 잘 저장한다.

#### 어디서 쓰이나요?

- 간단한 센서 데이터 저장, 파일 I/O 처리 등

#### array() 함수의 구조

```
array(typecode, initializer)
```

- typecode : 배열에 저장할 데이터의 자료형을 지정하는 한 글자 코드
- initializer : 초기데이터(보통 리스트)

#### 실무 및 학습에서 자주 사용하는 type코드 4가지

| 타입코드|타입   | 설명|: 주 사용 용도|
|---|---|---|---|
| "i"| int| 4byte 정수|: 일반적인 정수 저장용|
| "f"| float|4byte 실수|: 소수점 포함된 숫자 저장용|
| "d"| float|8byte 실수(double)|: 더 높은 정밀도의 실수 계산용|
| "B"| int|1byte 양의 정수(0~255)|: 바이트 데이터|

#### 리스트와 배열의 차이점(용어 설명)

- list(리스트) : 파이썬에서 기본적으로 제공하는 자료형, 여러 타입 가능
- array.array : 파이썬 표준 모듈, 같은 타입만 저장
- numpy.array : 외부라이브러리, 고성능 수치 연산용

|항목|list|   array|   numpy.array|
|---|---|---|---|
|제공방식|  기본자료형|    표준모듈(import)|   외부라이브러리|
|저장 자료형|  자유|   하나|   하나|
|차원|  기본은1차원(다차원 중첨)|   1차원|   1차원~n차원|        
|수학 연산|  직접 구현|   불편|   함수로 연산 가능|
|속도|  느림|    약간 빠름|    매우 빠른(C)|
|사용 빈도|  매우 높음|   거의 안씀|   데이터 처리에서 표준|

In [18]:
from array import array

In [20]:
# 배열 array.array 예제 1

# 일반적인 정수 저장
arr = array('i', [1, 2, 3, 4, 5])           # 동일한 타입의 숫자만 다룰때
print(arr)

# 일반적인 소수(실수) 저장
f_arr = array("f", [1.5, 2.5, 3.5, 4.5])        # 부동 소수점 약 7자리 정확도
print(f_arr)

# 더 정밀한 실수 계산이 필요할 때
d_arr = array("d", [3.14151416171781])          # 약 15~17자리 유효 숫자의 정밀도를 가진다.
print(d_arr)

# 0~255 범위의 바이트 저장
b_arr = array("B", [0, 155, 255])
print(b_arr)

array('i', [1, 2, 3, 4, 5])
array('f', [1.5, 2.5, 3.5, 4.5])
array('d', [3.14151416171781])
array('B', [0, 155, 255])


## 2) numpy.array

#### Numpy의 정의

- Numerical Python의 줄임말
- 수치

#### 특징

- 다차원 배열 객체인 numpy.array 제공
- 내부는 C언어로 구현되어 있어서 빠르다
- 반복문 없이 배열 전체에 연산 가능(-> 벡터화 연산)
- 선형대수, 통계 난수 생성등 과학 계산 기능 포함

```
[1, 2, 3, 4] -> 1차원 배열
[1, 2, 3, 4
 1, 2, 3, 4] -> 2행(가로줄) 4열(세로줄)의 다차원 배열
```

#### 왜 중요한가?

- 리스트보다 훨씬 빠르고, 효율적이며, 확장성 있는 수치 처리가 가능하다.
- 데이터분석, 머신러닝, 영상처리, 공학 계산등에서 사실상 표준 도구로 사용된다.

In [30]:
'''
[as]

- as는 별칭을 지정하는 키워드
- 넘파이를 np라는 이름을 불러오겠다

[as 왜 사용할까?]

1. 코드를 짧고 간결하게 쓰려고
2. 관례(대부분의 파이썬 개발자들은 넘파이를 np로 쓴다)
'''
import numpy as np

In [32]:
# 예제 1. 1차 배열
a = np.array([1,2,3])
print(a * 2)
print()

arr = array("i", [10, 20, 30])
print("배열 :", arr)
print("배열 * 2 :", arr * 2)

[2 4 6]

배열 : array('i', [10, 20, 30])
배열 * 2 : array('i', [10, 20, 30, 10, 20, 30])


In [34]:
# 예제 2. 2차 배열
arr2d = np.array([[1, 2, 3], [4, 5, 6]])      # 2차원 배열
result1 = arr2d + 100       # 모든 요소에 100을 더하기

print("원본 배열 : \n", arr2d)
print()
print("100을 더한 배열 : \n", result1)

원본 배열 : 
 [[1 2 3]
 [4 5 6]]

100을 더한 배열 : 
 [[101 102 103]
 [104 105 106]]


#### 브로드캐스팅

- 1차원 배열을 각 행에 더함
    - numpy의 핵심 기능 중 하나로, 서로 다른 크기의 배열 간 연산을 자동으로 맞춰주는 기능이다

#### 브로드캐스팅 예외

- a = np.array([[1, 2], [3, 4]])  ---->  2행 2열
- b = np.array([1, 2, 3])  ---->  1행 3열
- 차원이 안 맞아서 브로드캐스팅 불가능

In [39]:
# 예제 3. 2차 배열
arr2d = np.array([[10, 20, 30],[40, 50, 60]])           # 2차 배열
arr1d = array("i", [1, 2, 3])         # 1차원 배열
ressult = arr2d + arr1d

print("2차원 배열 :\n", arr2d)
print()
print("1차원 배열 :\n", arr1d)
print()
print("덧셈한 배열 :\n", ressult)

2차원 배열 :
 [[10 20 30]
 [40 50 60]]

1차원 배열 :
 array('i', [1, 2, 3])

덧셈한 배열 :
 [[11 22 33]
 [41 52 63]]


#### Numpy에서 자주 사용하는 통계 함수 정리

- **np.sum()**  :  총합 계산
- **np.mean()**  :  평균 계산
- **np.median()**  :  중앙값 계산
- **np.std()**  :  표준 편차 계산
- **np.var()**  :  분산 계산
- **np.min/max()**  :  최대/최소
- **np.argmax/argmin()**  :  최대, 최소값의 인덱스
- 문법 : np.원하는 연산 함수(연산할 배열 이름)

In [51]:
# 예제 1
scores = np.array([85, 90, 78, 92, 88])

print("합계 :", np.sum(scores))
print("평균 :", np.mean(scores))
print("중앙값 :", np.median(scores))
print("표준편차 :", np.std(scores))
print("분산 :", np.var(scores))
print("최소 :", np.min(scores))
print("최대 :", np.max(scores))
print("최대 인덱스 :", np.argmax(scores))
print("최소 인덱스 :", np.argmin(scores))

합계 : 433
평균 : 86.6
중앙값 : 88.0
표준편차 : 4.882622246293481
분산 : 23.84
최소 : 78
최대 : 92
최대 인덱스 : 3
최소 인덱스 : 2


#### 상관 계수

- np.corrcoef(arr1, arr2)
- 두 배열 간의 상관 관계(얼마나 같이 오르내리는지)를 계산
- 상관계수 1은 완벽한 양의 상관관계를 뜻한다.
- 반환값 : 2차원 행렬 형태의 상관계수
- 값 번위 : -1~1
    - 해석) 1 완벽히 같이 움직임, 0 무관, -1 반대로 움직임

In [55]:
# 상관 계수 예제
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

corr_m = np.corrcoef(x, y)
print(corr_m)

[[1. 1.]
 [1. 1.]]


# 자료구조 2. 연결리스트(LinkedList)

- 연결 리스트는 데이터를 차례대로 연결해 저장하는 구조이다.
- 각 데이터는 단순히 저장되는 것이 아니라, 자기 자신 + 다음 데이터를 가리키는 주소를 함께 갖고 있다.
- 포인터 : 메모리 주소를 저장하는 변수

### 연결 리스트의 주요 장점

1. 크기 제한 없음(동적 메모리 할당)
2. 삽입 | 삭제가 빠르다.
3. 메모리 효율적
4. 스택, 뮤 등 다양한 자료구조 구현에 유리하다.

### 언제 사용할까?

1. 데이터 양이 자주 바뀌는 경우
2. 중간 삽입/삭제가 자주 필요한 경우
3. 메모리 공간을 연속적으로 확보하기 힘든 경우

### 연결 리스트가 실생활에서 쓰이는 곳

1. 웹 브라우저의 "뒤로가기/앞으로가기"
    - [네이버] -> [구글] -> [다음]
3. 음악 재생 플레이 리스트

### 단일 연결 리스트(Single Linked List)

- 단일 연결 리스트는 한 방향으로만 연결되어 있는 가장 기본적인 형태의 연결 리스트다.
- [data | 주소] -> [data | 주소] -> [data | 주소]
- [체리 | 바나나 노드 주소] -> [바나나 | 수박의 노드 주소] -> [수박 | None]

### Node(노드)란?

- 연결 리스트에서 하나의 데이터 단위를 의미한다.
- [data | 포인터(다음 노드의 주소)]
- data : 저장할 실제 값
- 포인터 : 다음 노드의 주소

```
- 리스트 : [1, 2, 3, 4]
- [1 | 2의 주소값] -> [2 | 3의 주소값] -> [3 | 4의 주소값] -> [4 | None]
```

In [8]:
# Node 클래스 예제 1
# [데이터 | 빈주소]
class Node :
    def __init__(self, data):
        # 노드가 저장하는 데이터
        self.data = data
        # 다음 노드를 가리키는 포인터
        self.next = None

# 노드 생성
node1 = Node(10)      # 노드만 생성
node2 = Node(20)      # 노드만 생성

# node1 -> node2를 연결
node1.next = node2

# 출력
print("node1의 값 :", node1.data)
print()
print("node1이 가리키는 node2의 값 :", node1.next.data)

node1의 값 : 10

node1이 가리키는 node2의 값 : 20


In [10]:
# Node 클래스 예제 2
class Node :
    def __init__(self, data) :
        self.data = data
        self.next = None

n1 = Node(100)
n2 = Node(200)
n3 = Node(300)

n1.next = n2
n2.next = n3

print("n1의 값 :", n1.data)
print("n2의 값 :", n2.data)
print("n3의 값 :", n3.data)

print(id(n1))
print(id(n2))
print(id(n3))

n1의 값 : 100
n2의 값 : 200
n3의 값 : 300
2468753515696
2468800576592
2468800575920


### 헤드란?

```
['체리', '바나나', '수박']
head -> [체리 | 바나나의 주소] ->

- 연결 리스트의 시작점을 가리키는 포인터이다.
- 즉, 첫번째 노드를 가리키는 변수

-> 우리가 연결리스트를 탐색할 떄는 항상 head부터 출발
-> head가 없다면 연결리스트 전체를 알 수 없다.
```

In [14]:
# Node 클래스 예제 3
class Node :
    def __init__(self, data) :
        self.data = data
        self.next = None

f1 = Node("체리")
f2 = Node("바나나")
f3 = Node("수박")

f1.next = f2
f2.next = f3

# head 설정
head = f1

# 출력
current = head

while current : 
    print(current.data)
    current = current.next

체리
바나나
수박


### LinkedList에서 삽입(insert)이란?

- 연결 리스트의 원하는 위치에 새로운 노드를 추가하여 기존 노드들과 포인터로 연결하는 동작을 말한다.
- 연결 리스트는 연속된 메모리가 필요 없기 때문에, 중간이든 앞이든 뒤든 어디든지 삽입이 가능하다.

```
[이전 노드] -> [다음 노드]
[이전 노드] -> [새 노드 ] -> [다음노드]
```

In [18]:
# Node 클래스 삽입 예제
class Node :
    def __init__(self, data) :
        self.data = data
        self.next = None

f1 = Node("체리")
f2 = Node("바나나")
f3 = Node("수박")

f1.next = f2
f2.next = f3

# head 설정
head = f1

In [20]:
# 1.1. 맨 앞에 노드 삽입(딸기)
# 딸기 체리 바나나 수박
new_node = Node("딸기")
new_node.next = head        # 기존 리스트의 head를 new_node가 가리킴
head = new_node             # head를 new_node로 갱신(renewal)

In [22]:
# 1.2. 맨 앞 노드 삽입(블루베리)
# 블루베리 딸기 체리 바나나 수박
new_node2 = Node("블루베리")
new_node2.next = head
head = new_node2

In [24]:
# 2.1. 중간 노드 삽입(오렌지)
# 블루베리 딸기 체리 바나나 오렌지 수박
new_node3 = Node("오렌지")
target = f2                     # target은 바나나 노드
new_node3.next = target.next    # 오렌지가 수박을 가리킴
                                # 오렌지의 주소 = 수박 주소
target.next = new_node3

In [26]:
# 2.2 중간 노드 삽입(사과)
# 블루베리 딸기 사과 체리 바나나 오렌지 수박
new_node4 = Node("사과")
target = head.next                  # head는 블루베리 -> head.next는 딸기
new_node4.next = target.next        # 사과가 체리를 가리킴
target.next = new_node4             # 딸기가 사과를 가리킴

In [28]:
# 출력
current = head

while current : 
    print(current.data)
    current = current.next

블루베리
딸기
사과
체리
바나나
오렌지
수박


### 연결리스트(LinkedList)란?

- 데이터를 일렬로 저장하지만, 연속된 메모리 공간이 아니다.
- 각 데이터(노드)가 다음 데이터의 위치(주소)를 기억하는 방식으로 연결되어 있는 자료구조이다.

### 연결리스트 시각화

```
Head -> [데이터 | 다음 노드의 주소] -> [데이터 | 다음 노드의 주소] -> [데이터 | NONE] 
Head -> [체리] -> [수박] -> [블루베리]
```

### 연결리스트 특징

- 각 노드는 두가지 정보를 가진다.
    - 데이터 : 저장할 데이터
    - 주소 : 다음 노드를 가리키는 포인터(주소)
- 맨 앞 노드(Head)에서 시작해서 다음 노드를 따라가며 전체를 순회함.
- 데이터를 중간에 넣거나 삭제하기가 쉬움.
- **연결리스트는 순서를 유지하여, "자주 추가/삭제가 필요한 상황"에 유리한 자료구조이다.**

### 리스트 vs 연결리스트의 차이

|항목|리스트(배열 기반)|연결리스트|
|---|---|---|
|저장방식|연속된 메모리에 저장 : arr[0]|노드들이 포인터로 연결된다.|
|접근 속도|인덱스로 빠르게 접근|순차적으로 탐색해야함|
|삽입/삭제|중간 삽입/삭제 시 느림|중간 삽입/삭제가 빠르다.|
|크기|처음부터 크기를 정하거나 자동 증가|노드 추가할 때마다 크기가 유동적임|
|구현 난이도|파이썬에서는 매우 쉽다|직접 클래스를 만들어야 한다.|
|예시|학생 이름 목록, 상품 리스트 등|브라우저 뒤로가기, 큐, 힙, 그래프등|

- 리스트 삽입/삭제 예시
    - [1,2,3,4,5,7,8,9,10] 중간에 삭제를 할 경우 한 칸씩 다 앞으로 와야해서 느림

In [50]:
# 하나의 노드를 나타내는 클래스 정의
class Node :
    def __init__(self, data) :
        self.data = data        # 노드가 담고 있는 데이터
        self.next = None        # 다음 노드의 주소를 저장할 변수

In [52]:
# 연결 리스트 전체를 관리할 클래스 정의
class LinkedList :
    def __init__(self) :
        self.head = None        # 연결리스트의 시작점(처음엔 비어있음)

    # 리스트에 새 노드를 추가하는 메서드
    def append(self, data) :
        new_node = Node(data)   # 새 노드 생성

        # 리스트가 비어있다면
        if self.head is None :
            self.head = new_node        # head가 새 노드를 가리키게 함
            return
        
        # 리스트가 이미 있으면 -> 맨 끝까지 가야한다.
        current = self.head
        while current.next :            # current.next가 None이 아닐 동안 반복
            current = current.next      # 다음 노드로 이동
        current.next = new_node         # 마지막 노드의 next를 새 노드로 연결
                                        # [체리] -> [수박]
                                        # 지금 있는 노드가 새 노드한테 이어주는 것
    
    # 리스트에서 노드를 삭제하는 메서드
    def delete(self, data) :
        current = self.head         # 현재 노드를 head부터 시작
        prev = None                 # 이전 노드는 처음엔 없음

        while current :                     # 노드가 있는 동안 계속 반복
            if current.data == data :       # 찾는 데이터라면
                if prev is None :
                    # 첫 번째 노드를 삭제하는 경우
                    self.head = current.next
                else :
                    # 중간 또는 마지막 노드 삭제
                    prev.next = current.next
                print(f"`{data}`를 삭제했습니다.")
                return
            
            # 이전 노드를 현재로 저장하고
            prev = current
            # 다음 노드로 이동
            current = current.next

    # 리스트 전체 내용을 출력하는 메서드
    def print_all(self) :
        current = self.head             # 맨 처음 노드부터 시작

        while current :                 # current가 None이 아닐 때까지 반복
            print(current.data, end = ' -> ')       # 데이터 출력(줄바꿈 없이)
            current = current.next                  # 다음 노드로 이동
            
        print("None")           # 마지막 표시

In [54]:
# 빈 연결 리스트 생성
li = LinkedList()
li.append("체리")
li.append("바나나")
li.append("수박")
li.print_all()

li.delete("체리")
li.print_all()

체리 -> 바나나 -> 수박 -> None
`체리`를 삭제했습니다.
바나나 -> 수박 -> None


### 연결리스트 삭제 과정 ('라면'을 삭제하는 과정)

1. 처음부터 노드를 하나씩 살펴보기

    ```
    head -> [] -> [] ->
    current = self.head # 현재 노드를 head 부터 시작
    previous = None # 이전 노드는 처음엔 없음
    ```

2. current의 menu가 '라면'인지 확인

    ```
    previous = current
    current = current.next      # 다음 노드로 이동
    ```

3. current가 '라면'을 찾으면
    - 다음 노드로 이동

4. 이전 노드의 next 를 현재 노드의 다음 노드로 연결

    ```
    [김밥 | 라면의 주소] -> [라면 | 샐러드의 주소] -> [샐러드 | 돈까스 주소]
    [김밥 | 샐러드의 주소] -> [샐러드 | 돈까스주소]
    previous.next = current.next
    ```

In [66]:
class Menu :
    def __init__(self, menu) :
        self.menu = menu
        self.next = None

In [68]:
class LunchList :
    def __init__(self) :
        self.head = None
    
    def add_menu(self, menu) :
        new_menu = Menu(menu)
        
        if self.head is None :
            self.head = new_menu
            return 
        
        current = self.head

        while current.next :
            current = current.next

        current.next = new_menu

    def delete_menu(self, menu) :
        current = self.head
        prev = None

        while current :
            if current.menu == menu :
                if prev is None :
                    self.head = current.next
                else :
                    prev.next = current.next
                print(f"`{menu}`를 삭제했습니다.")
                return
        
        prev = current
        current = current.next

    def print_menu(self) :
        current = self.head
        
        if current : 
            print("오늘 먹은 점심 메뉴 :")

            while current :
                print(current.menu)
                current = current.next
            print("끝.")

In [70]:
lunch_menu = LunchList()
lunch_menu.add_menu("김밥")
lunch_menu.add_menu("라면")
lunch_menu.add_menu("샐러드")
lunch_menu.add_menu("돈까스")
lunch_menu.print_menu()

오늘 먹은 점심 메뉴 :
김밥
라면
샐러드
돈까스
끝.


# 자료구조 3. 스택(Stack)

### 스택(Stack)이란?

- LIFO 구조

### 스택의 정의

- 데이터를 쌓아 올리는 형태의 선형 자료구조(Linear Data Structure)로, 마지막에 넣은 데이터가 가장 먼저 나오는 후입선출(LIFO, Last In First Out) 구조이다.

### 스택의 동작 예시

- 예시 : 책을 쌓는 행위
- 삽입 순서 : A -> B -> C
- 꺼내는 순서 : C -> B -> A (가장 마지막에 넣은 것이 가장 먼저 나오는 구조이다.)

### 핵심 구성

- 삽입(push) : 데이터를 스택의 맨 위(top)에 넣는 작업
    - 삽입(append) : 파이썬에서는 push라는 함수가 없기에 append를 사용해야 한다.
- 삭제(pop) : 스택의 맨 위에서 데이터를 꺼내는 작업
- 조회(peek) : 삭제 없이 스택의 가장 위에 있는 데이터를 확인
- 비어있는지 확인(isEmpty) : 스택에 데이터가 있는지 확인

### 스택을 사용하는 이유

1. 실행 취소 기능 구현
2. 웹 브라우저의 뒤로가기
3. 함수 호출 기록(콜 스택)
4. 괄호 검사기, 수식 계산기 등에서의 구조적 데이터 처리

## 스택 예제 1.

In [79]:
stack = []

In [81]:
# push
stack.append("A")
stack.append("B")
stack.append("C")

# 현재 스택 상태 출력
print("현재 스택 :", stack)

현재 스택 : ['A', 'B', 'C']


In [87]:
print("스택 거꾸로 출력 :")
for item in reversed(stack) :       # 거꾸로 출력
    print(item)

스택 거꾸로 출력 :
C
B
A


In [89]:
# pop
print("pop :", stack.pop())

pop : C


In [91]:
# 조회
print("peek :", stack[-1])      # stack[-1] : 가장 마지막에 추가된 값을 의미한다.

peek : B


In [93]:
# 스택이 비어있는지 확인하기
print("스택이 비었나요? ", len(stack) == 0)

스택이 비었나요?  False


## 스택 예제 2.

In [96]:
books = []

In [98]:
books.append("동화책")
books.append("수학 문제집")
books.append("영어단어장")

In [100]:
print(">> 현재 책 더미 출력 :")

for book in books :
    print(book)

>> 현재 책 더미 출력 :
동화책
수학 문제집
영어단어장


In [102]:
print(f"1. {books.pop()}을 꺼냈습니다.")
print(f"2. {books.pop()}을 꺼냈습니다.")

1. 영어단어장을 꺼냈습니다.
2. 수학 문제집을 꺼냈습니다.


In [104]:
if len(books) > 0 :
    print("맨 위 책 확인 :", books[-1])
else :
    print("책 더미가 비어있습니다.")

맨 위 책 확인 : 동화책


## 스택 예제 3. 

- 스택을 이용해서 웹 브라우저의 "뒤로가기" 버튼 기능을 스택으로 구현해보는 예제 만들기
- "네이버" => "유튜브" => "위키백과"
- 뒤로가기를 누르면 -> 유튜브 ->네이버

In [107]:
# 방문한 페이지를 저장하는 스택
history = []

In [109]:
# 페이지 방문 (push, append)
def visit(page) :
    print(f"{page} 페이지에 방문했습니다.")
    history.append(page)
    for page in reversed(history) :
        print("-", page)

In [111]:
# 뒤로가기 (pop)
def go_back() :
    if len(history) == 0 :      # 방문한 기록이 아무것도 없으면, 즉  history가 비어있다면
        print("더 이상 뒤로 갈 수 없습니다.")
    
    else :
        # 가장 마지막에 방문한 페이지를 꺼내기
        last_page = history.pop()
        print(f"`{last_page}` 페이지에서 뒤로 갑니다.")

In [113]:
# 현재 페이지 확인 함수 (peek의 역할)
def current_page() :
    # 방문 기록이 없다면
    if len(history) == 0 :
        return "\n현재 페이지 없음\n"
    
    # 가장 마지막 페이지를 보여주기
    return f"\n현재 페이지 : {history[-1]}\n"

In [115]:
# 방문한 전체 페이지를 출력하는 함수
def print_history() :
    if not history:
        print("\n방문한 페이지가 없습니다.\n")
        return
    
    print("\n방문한 페이지 목록(최신순)")
    for page in reversed(history) :
        print("-", page)
    print("----------------")
    print("처음 페이지")

In [117]:
# 테스트 실행 -> 페이지 방문
visit("네이버")
visit("유튜브")
visit("위키백과")

네이버 페이지에 방문했습니다.
- 네이버
유튜브 페이지에 방문했습니다.
- 유튜브
- 네이버
위키백과 페이지에 방문했습니다.
- 위키백과
- 유튜브
- 네이버


In [119]:
# 현재 보고 있는 페이지 출력
print(current_page())


현재 페이지 : 위키백과



In [121]:
# 뒤로가기
go_back()
go_back()
go_back()
print_history()

`위키백과` 페이지에서 뒤로 갑니다.
`유튜브` 페이지에서 뒤로 갑니다.
`네이버` 페이지에서 뒤로 갑니다.

방문한 페이지가 없습니다.



## 스택 예제 4.스택을 활용한 계산기 입력 기록 만들기

- 스택 구조를 활용하여 사용자가 계산기를 사용하면서 입력한 숫자와 연산자를 기록하고, 되돌리기 기능을 통해 마지막 입력을 삭제할 수 있는 프로그램.

#### 프로그램 구성 설명

* 입력 기록 저장
1. 사용자가 입력한 숫자나, 기호(+, -, /, *)는 input_stack이라는 리스트에 저장된다.
2. 리스트는 스택처럼 동작하며, append로 추가하고, pop으로 삭제한다.

#### 명령 종류

- "숫자 또는 연산자" 입력 값을 스택에 저장
- undo : 최근 입력한 내용을 삭제
- print : 현재까지 입력한 내용을 모두 출력
- exit : 프로그램 종료

In [127]:
input_stack = []

In [129]:
# 입력(push)
def push(value) :
    print(f"입력 : {value}")
    input_stack.append(value)

In [131]:
# 최근 입력 삭제(pop)
def undo() :
    if len(input_stack) == 0 :
        print("되돌릴 입력값이 없습니다.")
    else :
        removed = input_stack.pop()
        print(f"되돌리기 : {removed} 삭제됨")

In [133]:
# 현재 입력 상태 출력
def print_state() :
    print("현재 입력 상태 :")

    if len(input_stack) == 0 :
        print("입력 없음")
    else :
        # 여러 문자열을 하나로 붙여주는 함수이다.
        # " " 공백을 넣는다는 의미이다.
        print(" ".join(input_stack))

In [135]:
# 사용자 입력 루프
while True :
    command = input("입력할 값(숫자, +, -, *, /) 또는 undo, print, exit 입력 : ")
    
    if command == "exit" :
        break
    elif command == "undo" :
        undo()
    elif command == "print" :
        print_state()
    else :
        push(command)

입력할 값(숫자, +, -, *, /) 또는 undo, print, exit 입력 :  5


입력 : 5


입력할 값(숫자, +, -, *, /) 또는 undo, print, exit 입력 :  +


입력 : +


입력할 값(숫자, +, -, *, /) 또는 undo, print, exit 입력 :  3


입력 : 3


입력할 값(숫자, +, -, *, /) 또는 undo, print, exit 입력 :  *


입력 : *


입력할 값(숫자, +, -, *, /) 또는 undo, print, exit 입력 :  2


입력 : 2


입력할 값(숫자, +, -, *, /) 또는 undo, print, exit 입력 :  undo


되돌리기 : 2 삭제됨


입력할 값(숫자, +, -, *, /) 또는 undo, print, exit 입력 :  10


입력 : 10


입력할 값(숫자, +, -, *, /) 또는 undo, print, exit 입력 :  print


현재 입력 상태 :
5 + 3 * 10


입력할 값(숫자, +, -, *, /) 또는 undo, print, exit 입력 :  exit


In [137]:
# [나의 풀이]
input_stack = []

while True : 
    user = input("입력할 값 : ")
    
    if user == "print" :
        print("현재 입력 상태 :")
        for item in input_stack :
            print(item, end=" ")
        break

    elif user == "undo" :
        last_item = input_stack.pop()
        print(f"되돌리기 : {last_item} 삭제됨")
        print("input_stack :", input_stack)
        print()

    else :
        print(f"입력 : {user}")
        input_stack.append(user)
        print("input_stack :", input_stack)
        print()

입력할 값 :  5


입력 : 5
input_stack : ['5']



입력할 값 :  +


입력 : +
input_stack : ['5', '+']



입력할 값 :  3


입력 : 3
input_stack : ['5', '+', '3']



입력할 값 :  *


입력 : *
input_stack : ['5', '+', '3', '*']



입력할 값 :  2


입력 : 2
input_stack : ['5', '+', '3', '*', '2']



입력할 값 :  undo


되돌리기 : 2 삭제됨
input_stack : ['5', '+', '3', '*']



입력할 값 :  10


입력 : 10
input_stack : ['5', '+', '3', '*', '10']



입력할 값 :  print


현재 입력 상태 :
5 + 3 * 10 

# 자료구조 4. 큐(Queue)

- 데이터를 순서대로 저장하고 꺼내는 선형자료구조로 먼저 들어간 데이터가 먼저 나오는 선입선출(FIFO, First In First Out) 구조이다.
- [Front] => 1 -> 2 -> 3 
    - 1이 가장 먼저 들어와서 가장 먼저 나간다.
- 선입선출 : 데이터를 순서대로 저장하고 꺼내는 선형 자료구조

### 실생활 예시

- 버스 정류장 줄서기 : 먼저 선 사람부터 탑승
- 프린터 작업 대기열 : 먼저 보낸 문서부터 출력
- https://velog.io/@sbinha/%EC%8A%A4%ED%83%9D-%ED%81%90

### 왜 큐가 필요할까?

1. 순차적인 작업 처리가 필요한 곳에 적합
2. 실시간 처리 시스템(프린터, 요청 처리등에 사용)
3. BFS(너비 우선 탐색)와 같은 알고리즘에서 핵심 자료구조로 활용

### 핵심 개념(필요한 함수)

- Enqueue(인큐) : 데이터를 뒤쪽에서 넣는 작업
- Dequeue(디큐) : 데이터를 앞쪽에서 꺼내는 작업
- Peek : 삭제 없이 가장 앞의 데이터를 확인
- isEmpty : 큐가 비어있는지 확인

## (1) 리스트로 큐

In [146]:
# 리스트로 큐 구현 (비효율)
#   : 리스트는 배열처럼 생겨서, 앞에서 꺼내면 뒤에 있는 것을 전부 앞으로 밀어야 한다.
queue = []

In [148]:
# enqueue
queue.append("고객1")
queue.append("고객2")
queue.append("고객3")
print("현재 큐 :", queue)

현재 큐 : ['고객1', '고객2', '고객3']


In [151]:
# dequeue : 값을 꺼내는 작업
print("처리 중 :", queue.pop(0))
print("처리 중 :", queue.pop(0))

처리 중 : 고객1
처리 중 : 고객2


## (2) 모듈 사용 큐

In [154]:
# 효율적인 큐 구현

# deque 모듈 가져오기(큐 기능 사용하기 위해서)
from collections import deque

In [156]:
# 비어있는 큐 생성
queue = deque()

In [158]:
# 큐에 넣기 (enqueue)
queue.append("사과")
queue.append("바나나")
queue.append("체리")
print("현재 큐 :", queue)

현재 큐 : deque(['사과', '바나나', '체리'])


### 큐 예제 1. 프린터 출력 대기열 시뮬레이션

In [168]:
from collections import deque

In [170]:
# 프린터 큐를 나타내는 클래스 정의
class PrinterQueue :
    # 생성자
    def __init__(self) :
        # 출력할 작업들을 저장할 큐
        self.jobs = deque()

    # 작업을 큐에 추가하는 메서드
    def add_job(self, job) :
        self.jobs.append(job)       # 큐의 뒤쪽에 작업 추가
        print(f"프린터 작업 추가 : {job}")

    # 작업을 큐에서 꺼내어 처리하는 메서드
    def process_job(self) :
        # 대기 중인 작업이 있으면
        if self.jobs :
            job = self.jobs.popleft()       # 큐의 앞쪽 작업 꺼냄
            # .pop : 오른쪽(뒤쪽) 요소를 꺼냄 -> 스택처럼 동작
            # .popleft : 왼쪽(앞쪽) 요소를 꺼냄 -> 큐처럼 동작

            print(f"프린터 출력 중 : {job}")

        # 대기 중인 작업이 없으면 (대기열이 비었을 경우)
        else :
            print("대기 중인 작업이 없습니다.")

In [172]:
# printerQueue 클래스의 인스턴스를 생성
printer = PrinterQueue()

In [174]:
# 출력할 작업 2개를 추가
printer.add_job("파일1.pdf")
printer.add_job("파일2.pdf")

프린터 작업 추가 : 파일1.pdf
프린터 작업 추가 : 파일2.pdf


In [176]:
# 작업을 하나씩 처리
printer.process_job()
printer.process_job()

프린터 출력 중 : 파일1.pdf
프린터 출력 중 : 파일2.pdf


### 큐 예제 2. 놀이공원 대기열 시뮬레이션

In [182]:
# 큐 선언
from collections import deque

In [192]:
# 놀이공원 입장 대기열을 관리하는 클래스
class partQueue :
    # 생성 
    def __init__(self) :
        self.line = deque()

    # 사람들이 줄을 서는 메서드(추가)
    def join_line(self, name) :
        self.line.append(name)
        print(f"{name}님이 줄을 섰습니다.")

    # 입장 처리 메서드(빼기)
    def enter_park(self) :
        if self.line :
            name = self.line.popleft()
            print(f"{name}님이 입장하셨습니다.")

        else :
            print("줄에 아무도 없습니다.")

In [194]:
queue = partQueue()

In [196]:
queue.join_line("철수")
queue.join_line("영희")
queue.join_line("길동")

철수님이 줄을 섰습니다.
영희님이 줄을 섰습니다.
길동님이 줄을 섰습니다.


In [198]:
queue.enter_park()
queue.enter_park()
queue.enter_park()

철수님이 입장하셨습니다.
영희님이 입장하셨습니다.
길동님이 입장하셨습니다.
